---
# defaults file for tmux
tmux_packages:
  - tmux

# Default path to the config file for tmux
tmux_path_config: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux.conf"

# Default template path within ./templates for the config file.
tmux_config_template: "{{ role_path }}/templates/tmux.conf.j2"

# Default configuration for tmux
tmux_config: []

# Default user for tmux
tmux_owner: "{{ lookup('ansible.builtin.env', 'USER') }}"

# Default group for tmux
tmux_group: "{{ lookup('ansible.builtin.env', 'USER') }}"
